// demo/svelte-app/src/App.svelte
<main>
  <div>
    <h1>Google</h1>
    <p class="poppins">Poppins</p>
    <p class="press-start">Press Start 2P</p>

    <h1>Bunny</h1>
    <p class="bunny-aclonica">Aclonica</p>
    <p class="bunny-allan">Allan</p>

    <h1>FontShare</h1>
    <p class="font-share-panchang">Panchang</p>

    <h1>FontSource</h1>
    <p class="font-source-luckiest">Luckiest</p>

    <h1>Local</h1>
    <p class="local">Local font</p>
  </div>
</main>
<style>

p {
  font-size: x-large;
}

.google-poppins {
  font-family: "Poppins", sans-serif;
}

.google-press-start {
  font-family: "Press Start 2P", sans-serif;
}

.bunny-aclonica {
  font-family: "Aclonica", sans-serif;
}

.bunny-allan {
  font-family: "Allan", sans-serif;
}

.font-share-panchang {
  font-family: "Panchang", sans-serif;
}

.font-source-luckiest {
  font-family: "Luckiest Guy", sans-serif;
}

@font-face {
  font-family: "Black Fox";
  src: url("./black-fox.ttf");
}

.local {
  font-family: "Black Fox", sans-serif;
}
</style>

// demo/vue-app/src/App.vue
<template>
  <div>
    <h1>Google</h1>
    <p class="poppins">Poppins</p>
    <p class="press-start">Press Start 2P</p>

    <h1>Bunny</h1>
    <p class="bunny-aclonica">Aclonica</p>
    <p class="bunny-allan">Allan</p>

    <h1>FontShare</h1>
    <p class="font-share-panchang">Panchang</p>

    <h1>FontSource</h1>
    <p class="font-source-luckiest">Luckiest</p>

    <h1>Local</h1>
    <p class="local">Local font</p>
  </div>
</template>

<style scoped>
p {
  font-size: x-large;
}

.google-poppins {
  font-family: "Poppins", sans-serif;
}

.google-press-start {
  font-family: "Press Start 2P", sans-serif;
}

.bunny-aclonica {
  font-family: "Aclonica", sans-serif;
}

.bunny-allan {
  font-family: "Allan", sans-serif;
}

.font-share-panchang {
  font-family: "Panchang", sans-serif;
}

.font-source-luckiest {
  font-family: "Luckiest Guy", sans-serif;
}

@font-face {
  font-family: "Black Fox";
  src: url("./black-fox.ttf");
}

.local {
  font-family: "Black Fox", sans-serif;
}
</style>
